### ISSUE TITLE
AC skill is not responding 

### ISSUE THREAD

**Issue by littlerain14** [TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#2]
Hi all,

I  like this skill so much.  it make my old Airconditioner working by voice greatly.
But currently, after some days when I successfully created alexa skill, this custom skill may not worked well.
Alexa only allow to turn off and turn on AC. When I said "alexa, set AC to 28 degree, it alway respond that "Sorry, AC is not responding". Please help me to reslove this issue.

Thanks

**Comment by TomerFi** [comment]
@littlerain14 
That's weird.

Can you please the lambda log maybe there is something there that will help us figure it out?

**Comment by littlerain14** [comment]
Hi TomerFi,
Thank you for responding my answer.
Here is the log I got from Cloudwatch in AWS (after alexa respond "sorry, AC is not respoding"

`START RequestId: ff2bf4de-4a80-11e8-9358-73aaa652a114 Version: $LATEST
END RequestId: ff2bf4de-4a80-11e8-9358-73aaa652a114
REPORT RequestId: ff2bf4de-4a80-11e8-9358-73aaa652a114	Duration: 10009.99 ms	Billed Duration: 10000 ms Memory Size: 128 MB	Max Memory Used: 44 MB	
2018-04-28T01:11:03.979Z ff2bf4de-4a80-11e8-9358-73aaa652a114 Task timed out after 10.01 seconds`

**Comment by TomerFi** [comment]
Do you perhaps see any errors in your HA log,
So we can you verify the API request arrives safety to your HA environment?

If you can share your `endpoints_config.json` file?

**Comment by littlerain14** [comment]
Hi TomerFi,

Here is my endpoints_config.json

`[{
	"endpoint_unique_id": "climate_living_room_ac",
	"alexa_friendly_name": "AC",
	"status_input_boolean": "input_boolean.lr_ac_status",
	"degrees_control": {
		"degrees_input_text": "input_text.lr_ac_temp_text",
		"min_degree": 18,
		"max_degree": 30
	},
	"mode_input_select": "input_select.lr_ac_mode"
}]`

It 's very strange that working correctly sometime (normaly when I restart Hass server), after that (about 5 minute) when I try to control the temperature, the issues occured again "sorry, AC is not responding"

**Comment by TomerFi** [comment]
@littlerain14 
So you can say:
Alexa, turn on/off the living room ac
And it works well.

And you can say:
Alexa, set the living room ac temperature to 24
But that only works for a couple of minutes and then stops working.

Did I understand correctly?
If so, it sounds like you HA API stops responding.

**Comment by littlerain14** [comment]
Hi TomerFI,
You understand corectly.
Do you have any recommendation for my situation? 

Alexa still understand to turn on/off AC device. Why she cannot change the temperature of AC? :(

**Comment by TomerFi** [comment]
First maybe try to set the following components' log level to 'debug':
```yaml
logger:
  default: error
  logs:
    homeassistant.components.http.view: debug
    homeassistant.components.websocket_api: debug
```
You can also add `homeassistant.components.automation` and `homeassistant.components.script` so you can follow the all process in the log file (you can even do the same for `input_text`, `input_select` and so on...).
Just remmember that the HA info screen is always set to `warning` level, so to see the `debug` logs you'll need to open the log-file.

Second thing you can try is this: When you ask the skill to set the temperature, it sends the following POST request towards your home assistant, maybe try and send it yourself and see if you get any error. I use [Postman](https://www.getpostman.com/) for stuff like this.

Url (as configured in `hass_api_config.json`):
`https://#place your dns name here#:443/api/services/input_text/set_value`

Body:
```json
{
    "entity_id": "#place the entity id set as degrees_input_text in endpoints_config.json#",
    "value": "#place the desired temperature here#"
}
```

Headers:
`Accept: application/json`
`Content-Type: application/json`
`x-ha-access: #place your api password here, as set in hass_api_config.json#`

**Comment by littlerain14** [comment]
Hi TomerFi,

THank you very much for responding 

I follow your instruction to add logger component to configuration file

and here is the result I got from log
  
```
friendly_name=Humidity @ 2018-05-04T10:36:01.054670+07:00>, 'new_state': <state sensor.broadlink_sensor_humidity=76.1; unit_of_measurement=%, friendly_name=Humidity @ 2018-05-04T10:37:03.056360+07:00>}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2018, 5, 4, 3, 37, 3, 56515, tzinfo=<UTC>)}}
2018-05-04 10:37:48 INFO (MainThread) [homeassistant.components.http.view] Serving /api/error/all to 27.67.31.235 (auth: True)
2018-05-04 10:37:53 INFO (MainThread) [homeassistant.components.http.view] Serving /api/error_log to 27.67.31.235 (auth: True)
```

As I understand this is the api error, correctly?
Can I need to add API component in configuration.yaml, and what is the data for this component.
Sorry, Im really newbie for this.

**Comment by TomerFi** [comment]
That's ok, it's a `INFO` level message.
The `http.view` component is also responsible for serving data to the frontend.
What it's saying here is that the `error log` was served, meaning you probably entered the Information panel in HA where you can see the logs which were served to that panel by `http.view`.

We need to be looking for the `websocket_api` logs and find the request and response for a successful operation and the ones for a failed operation and try to compare them and see what went wrong in the process.
Alexa smart home skills also requires constant state reports especially before controlling anything, which means you'll also see `websocket_api` request for information retrieval, so try to keep an eye out for these type of requests too.

The thing is, I don't actually believe that HA's web api stopped responding after a couple of requests, what I think is happening here is that the entities are set to wrong values.

I'll give you an example:
Let's say your current entities states are:
- state:OFF
- temperature:24
- mode:COOL

When you ask alexa to turn on the ac, it will send a state report request and try to parse the above values, the operation will succeed and then alexa will send a request to turn on the ac.
Now the ac is on, and the your entities states are:
- state:ON
- temperature:24
- mode:COOL

Now when you ask alexa to set the temperature to 25, it will again send a state report request and try to parse the above values, the operation will succeed and then alexa will send a request to set the temperature to 25.
For this example, let's the operation has succeeded but the input_text value was messed up and was set to `unknown` or `367.25`, or any other value that is un-parsable  as a temperature for that manner.
So now, your entities states are:
- state:ON
- temperature:unknown
- mode:COOL

Now when you ask alexa to set the temperature to 23, alexa will send a state report that will fail because `unknown` is not a legitimate temperature, and alexa will respond `"device is not responsive"`.

If this is the case, we might find the answer in the state reports responses by the `websocket_api`, you won't see it as an error on HA side, because as far as HA concern, it's not. But you will be able to see the values returning to alexa and see if they are legitimate ac states.

**Comment by TomerFi** [comment]
I'm closing this issue as it's been a long time since the last response and this repository is no longer maintained.

Please feel free to continue the conversation if needed.
